### ISSUE TITLE
Incorrect defaults for `--format` option in management command

### ISSUE THREAD

**Issue by zerolab** [Frojd/wagtail-redirect-importer#4]
The default `,` value for the `--format` option in the management command is incorrect.
Tablib expects it to be one of "csv", "tsv", "xls", "json" (and any of the supported ones in the https://tablib.readthedocs.io/en/stable/formats/#csv list)

**Comment by marteinn** [comment]
https://github.com/Frojd/wagtail-redirect-importer/blob/develop/wagtail_redirect_importer/management/commands/import_redirects.py#L46 = 🤦‍♂ . Thanks for reporting @zerolab, we'll make sure this gets addressed in the next release :)

**Comment by marteinn** [comment]
I've changed the logic in CLI, format should not be required, format uses a choice list (generated by tablib) so we can better represent choices to users and finally solved a bug when using file extension as format. Closing this and any related error will get a new issue.
